import express from "express";
import dotenv from "dotenv";
import cors from "cors";
import helmet from "helmet";
import morgan from "morgan";
import { PrismaClient } from "@prisma/client";
import authRouter from "./routes/auth.js";
import projectRouter from "./routes/projects.js";
import ewRouter from "./routes/earlyWarnings.js";
import ceRouter from "./routes/compEvents.js";
import noticeRouter from "./routes/notices.js";
import paymentRouter from "./routes/payments.js";
dotenv.config();
const app = express();
const prisma = new PrismaClient();
app.use(helmet());
app.use(cors({ origin: process.env.APP_BASE_URL || "http://localhost:5173", credentials: true }));
app.use(express.json());
app.use(morgan("dev"));
app.get("/api/health", (req, res) => res.json({ ok: true }));
app.use("/api/auth", authRouter);
app.use("/api/projects", projectRouter);
app.use("/api/ews", ewRouter);
app.use("/api/ces", ceRouter);
app.use("/api/notices", noticeRouter);
app.use("/api/payments", paymentRouter);
app.use((err, req, res, next) => { console.error(err); res.status(500).json({ error: "Internal server error" }) });
const port = process.env.PORT || 3001;
app.listen(port, () => console.log(`ACE Contracts backend listening on port ${port}`));
